import express from "express";
import { authRouter } from "./auth/routes.js";
import { query } from "./db/pool.js";

const app = express();
app.set("trust proxy", 1);
app.use(express.json());
app.use("/api/auth", authRouter);

const server = app.listen(4555);
const BASE = "http://127.0.0.1:4555/api/auth";

let pass = 0, fail = 0;
function check(label, cond, extra = "") {
  if (cond) { pass++; console.log(`  PASS  ${label}`); }
  else { fail++; console.log(`  FAIL  ${label} ${extra}`); }
}

async function post(path, body, headers = {}) {
  const r = await fetch(BASE + path, {
    method: "POST",
    headers: { "Content-Type": "application/json", ...headers },
    body: JSON.stringify(body),
  });
  return { status: r.status, body: await r.json().catch(() => ({})) };
}

// The mailer is in dev mode (no SMTP env), so codes are logged not sent.
// Read them straight from the table instead — we only need to prove the
// hash matches, which bcrypt.compare does inside checkCode.
import bcrypt from "bcrypt";
async function findCode(email) {
  const { rows } = await query(
    `SELECT code_hash FROM email_verification_codes WHERE LOWER(email) = $1 AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1`,
    [email.toLowerCase()]
  );
  if (!rows[0]) return null;
  for (let i = 100000; i < 1000000; i++) {
    if (await bcrypt.compare(String(i), rows[0].code_hash)) return String(i);
  }
  return null;
}
// Brute-forcing 900k bcrypt hashes is not viable in a test, so instead
// capture the code as it's generated by spying on console.log from the
// dev-mode mailer.
const sentMail = [];
const realLog = console.log;
console.log = (...args) => {
  const line = args.join(" ");
  if (line.includes("[dev] Would send email")) sentMail.push(line);
};

function lastCodeFor(email) {
  const entry = [...sentMail].reverse().find((m) => m.includes(email));
  if (!entry) return null;
  const m = /كود تأكيد بريدك في كنف: (\d{6})/.exec(entry);
  return m ? m[1] : null;
}



async function run() {
  const results = [];
  const log = (s) => results.push(s);

  const EMAIL = "Sara.Test@Example.com";
  const PASSWORD = "kanaf-strong-pass-9";

  // 1. Registration writes a row
  let r = await post("/register", {
    name: "سارة", email: EMAIL, password: PASSWORD,
    confirmedAdult: true, agreedPolicy: true,
  });
  log(["register returns 201", r.status === 201, JSON.stringify(r.body)]);

  const { rows: userRows } = await query(`SELECT id, name, email, email_verified_at, confirmed_adult FROM users`);
  log(["a users row now exists", userRows.length === 1, JSON.stringify(userRows)]);
  log(["email stored lowercased", userRows[0]?.email === "sara.test@example.com", userRows[0]?.email]);
  log(["starts unverified", userRows[0]?.email_verified_at === null]);

  // 2. Login before verification is refused with a distinct reason
  r = await post("/login", { email: EMAIL, password: PASSWORD });
  log(["unverified login -> 403 email_not_verified", r.status === 403 && r.body.error === "email_not_verified", JSON.stringify(r.body)]);

  // 3. Wrong code increments attempts, doesn't verify
  r = await post("/verify-email", { email: EMAIL, code: "000000" });
  log(["wrong code rejected", r.status === 400 && r.body.error === "incorrect", JSON.stringify(r.body)]);
  log(["attemptsLeft reported", r.body.attemptsLeft === 4, String(r.body.attemptsLeft)]);

  // 4. Correct code verifies and returns a session
  const code = lastCodeFor("sara.test@example.com");
  log(["code captured from outgoing mail", Boolean(code), String(code)]);
  r = await post("/verify-email", { email: EMAIL, code });
  const session = r.body;
  log(["verify returns 200 + tokens", r.status === 200 && !!session.accessToken && !!session.refreshToken, JSON.stringify(r.body).slice(0, 120)]);
  log(["user marked verified", session.user?.emailVerified === true]);

  // 5. Code can't be replayed
  r = await post("/verify-email", { email: EMAIL, code });
  log(["code is single-use", r.status === 400 && r.body.error === "no_code", JSON.stringify(r.body)]);

  // 6. Login now works
  r = await post("/login", { email: "SARA.TEST@EXAMPLE.COM", password: PASSWORD });
  log(["login works, case-insensitive email", r.status === 200 && !!r.body.accessToken, String(r.status)]);
  const loginSession = r.body;

  // 7. Wrong password
  r = await post("/login", { email: EMAIL, password: "wrong-password-here" });
  log(["wrong password -> 401", r.status === 401 && r.body.error === "invalid_credentials"]);

  // 8. Unknown account returns the SAME error as a wrong password
  r = await post("/login", { email: "nobody@example.com", password: "wrong-password-here" });
  log(["unknown account gives identical error", r.status === 401 && r.body.error === "invalid_credentials", JSON.stringify(r.body)]);

  // 9. /me with the access token
  let me = await fetch(BASE + "/me", { headers: { Authorization: `Bearer ${loginSession.accessToken}` } });
  const meBody = await me.json();
  log(["/me resolves the bearer token", me.status === 200 && meBody.user?.email === "sara.test@example.com", JSON.stringify(meBody)]);

  me = await fetch(BASE + "/me", { headers: { Authorization: "Bearer garbage.token.here" } });
  log(["/me rejects a forged token", me.status === 401]);

  // 10. Refresh rotates
  r = await post("/refresh", { refreshToken: loginSession.refreshToken });
  log(["refresh returns a new pair", r.status === 200 && r.body.refreshToken !== loginSession.refreshToken, String(r.status)]);
  const rotated = r.body.refreshToken;

  r = await post("/refresh", { refreshToken: loginSession.refreshToken });
  log(["old refresh token is dead after rotation", r.status === 401, JSON.stringify(r.body)]);

  // 11. Logout revokes
  r = await post("/logout", { refreshToken: rotated });
  log(["logout returns ok", r.status === 200]);
  r = await post("/refresh", { refreshToken: rotated });
  log(["revoked token can't refresh", r.status === 401]);

  // 12. Duplicate registration doesn't reveal the account
  r = await post("/register", {
    name: "شخص آخر", email: EMAIL, password: "another-password-1",
    confirmedAdult: true, agreedPolicy: true,
  });
  log(["duplicate register still returns 201", r.status === 201, JSON.stringify(r.body)]);
  const { rows: afterDup } = await query(`SELECT count(*)::int AS n FROM users`);
  log(["no second row created", afterDup[0].n === 1, JSON.stringify(afterDup)]);
  const { rows: nameCheck } = await query(`SELECT name FROM users WHERE LOWER(email)='sara.test@example.com'`);
  log(["verified account untouched by the duplicate", nameCheck[0].name === "سارة", nameCheck[0].name]);

  // 13. Password still works after the duplicate attempt
  r = await post("/login", { email: EMAIL, password: PASSWORD });
  log(["original password unchanged", r.status === 200, String(r.status)]);

  // 14. bcrypt 72-byte guard
  r = await post("/register", {
    name: "طويل", email: "long@example.com", password: "كلمة-مرور-طويلة-جدا-بالعربية-تتجاوز-حد-اثنين-وسبعين-بايت-بسهولة",
    confirmedAdult: true, agreedPolicy: true,
  });
  log(["over-72-byte password rejected", r.status === 400 && r.body.error === "password_too_long", JSON.stringify(r.body)]);

  // 15. Other validation
  r = await post("/register", { name: "ق", email: "x@y.com", password: PASSWORD, confirmedAdult: true, agreedPolicy: true });
  log(["short name rejected", r.status === 400 && r.body.error === "name_required"]);
  r = await post("/register", { name: "تجربة", email: "x@y.com", password: PASSWORD, confirmedAdult: false, agreedPolicy: true });
  log(["missing 18+ confirmation rejected", r.status === 400 && r.body.error === "adult_confirmation_required"]);
  r = await post("/register", { name: "تجربة", email: "x@y.com", password: "short", confirmedAdult: true, agreedPolicy: true });
  log(["short password rejected", r.status === 400 && r.body.error === "password_too_short"]);
  r = await post("/register", { name: "تجربة", email: "not-an-email", password: PASSWORD, confirmedAdult: true, agreedPolicy: true });
  log(["bad email rejected", r.status === 400 && r.body.error === "invalid_email"]);

  // 16. Resend cooldown
  r = await post("/register", { name: "جديد", email: "fresh@example.com", password: PASSWORD, confirmedAdult: true, agreedPolicy: true });
  const firstOk = r.status === 201;
  r = await post("/resend-code", { email: "fresh@example.com" });
  log(["resend blocked by 60s cooldown", firstOk && r.status === 429 && r.body.error === "cooldown", JSON.stringify(r.body)]);

  // 17. Login lockout
  for (let i = 0; i < 8; i++) await post("/login", { email: EMAIL, password: "bad-password-attempt" });
  r = await post("/login", { email: EMAIL, password: PASSWORD });
  log(["account locks after 8 failures, even with the right password", r.status === 429 && r.body.error === "account_locked", JSON.stringify(r.body)]);

  console.log = realLog;
  for (const [label, cond, extra] of results) check(label, cond, extra ? `(got: ${extra})` : "");
  console.log(`\n  ${pass} passed, ${fail} failed`);
  server.close();
  process.exit(fail > 0 ? 1 : 0);
}

run().catch((e) => { console.log = realLog; console.error(e); server.close(); process.exit(1); });
